Repository GINK-SS/bab-friend, pull requests merged in 2024-01, with the labels that each got.

#22 [refac-13] 유저 인증 및 라우터 구조 정리
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/apis/auth.ts
  src/apis/axios.ts
  src/apis/posts.ts
  src/apis/userEdit.ts
  src/components/MainLayout.tsx
  src/components/Modal/index.tsx
  src/components/ProfileInfo/index.tsx
  src/components/SideBar/index.tsx
  src/components/common/Header/index.tsx
  src/hoc/AuthChecker.tsx
  src/hoc/route/PrivateRoute.tsx
  src/hoc/route/PublicRoute.tsx
  src/index.tsx
  src/pages/Auth.tsx
  src/pages/CreatePostContent/index.tsx
  src/pages/PostDetail/index.tsx
  src/pages/PostDetail/styles.ts
  src/pages/SignIn.tsx
  src/recoil/atoms/auth.ts
  src/recoil/atoms/modal.ts
  src/recoil/atoms/user.ts
  src/types/api.ts
  src/types/auth.ts
  src/types/user.ts
  src/types/userEdit.ts
  tsconfig.paths.json
Labels: Refac

#35 [feat-32] msw 설정 완료
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/index.tsx
  src/mocks/api/board.ts
  src/mocks/api/data/boardData.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  tsconfig.paths.json
Labels: Feat

#36 [feat-28] 홈 화면 데이터 불러오기 구현 완료
  src/apis/board.ts
  src/components/Board/index.tsx
  src/components/Board/styles.ts
  src/components/Calendar/index.tsx
  src/mocks/api/data/boardData.ts
  src/pages/Home.tsx
  src/types/board.ts
  src/utils/.gitkeep
  src/utils/formatDate.ts
Labels: Feat

#38 [feat-37] 메인 페이지 디자인 구현 완료
  src/components/BabTemp/styles.ts
  src/components/Board/index.tsx
  src/components/Board/styles.ts
  src/components/CommentInput/styles.ts
  src/components/KakaoMapModal/styles.ts
  src/components/ProfileInfo/styles.ts
  src/components/SelectOption/styles.ts
  src/components/SideBar/styles.ts
  src/components/common/Header/styles.ts
  src/components/common/Input/styles.ts
  src/components/common/Spinner/styles.ts
  src/components/common/Textarea/styles.ts
  src/index.tsx
  src/mocks/api/data/boardData.ts
  src/pages/CreatePostContent/styles.ts
  src/style/theme.ts
  src/types/board.ts
  src/types/styled.d.ts
Labels: Feat

#40 [feat-34] 게시글 상세, 댓글 mock 데이터 바인딩
  src/apis/board.ts
  src/apis/comment.ts
  src/components/CommentDisplay/index.tsx
  src/components/CommentInput/index.tsx
  src/components/PostContent/index.tsx
  src/components/PostOption/index.tsx
  src/components/PostOption/styles.ts
  src/components/common/Textarea/index.tsx
  src/mocks/api/boardDetail.ts
  src/mocks/api/comment.ts
  src/mocks/api/data/boardDetailData.ts
  src/mocks/api/data/comment.ts
  src/mocks/handlers.ts
  src/pages/PostDetail/index.tsx
  src/types/board.ts
  src/types/comment.ts
Labels: Feat

#42 [feat-41] Kakao Map API 현재 위치기반 지도 생성, 마커 클릭시 주소 생성
  src/components/KakaoMapModal/index.tsx
  src/components/KakaoMapModal/styles.ts
  src/components/SelectOption/index.tsx
  src/components/SelectOption/styles.ts
  src/components/common/Input/styles.ts
  src/recoil/atoms/posts.ts
Labels: Feat

#46 [feat-43] 유저정보 수정 프로필 이미지 url 수정
  src/components/BabTemp/index.tsx
  src/components/ProfileInfo/index.tsx
  src/components/SideBar/index.tsx
  src/components/SideBar/styles.ts
  src/components/common/ProgressBar/index.tsx
  src/components/common/ProgressBar/styles.ts
Labels: Chore
