Repository GINK-SS/bab-friend, pull requests merged in 2024-02, with the labels that each got.

#50 [feat-47]게시글 수정,삭제,약속확정 기능 구현
  src/Router.tsx
  src/apis/board.ts
  src/apis/posts.ts
  src/components/Board/index.tsx
  src/components/BoardDetailContent/index.tsx
  src/components/BoardDetailContent/styles.ts
  src/components/BoardDetailOption/index.tsx
  src/components/BoardDetailOption/styles.ts
  src/components/Calendar/index.tsx
  src/components/KakaoMapModal/index.tsx
  src/components/PostContent/index.tsx
  src/components/PostContent/styles.ts
  src/components/SelectBoardOption/index.tsx
  src/components/SelectBoardOption/styles.ts
  src/components/SelectOption/index.tsx
  src/components/SideBarContent/index.tsx
  src/components/UpdateBoard/index.tsx
  src/components/UpdateBoard/styles.ts
  src/components/common/Header/index.tsx
  src/components/common/Input/index.tsx
  src/mocks/api/data/boardDetailData.ts
  src/pages/BoardDetail/index.tsx
  src/pages/BoardDetail/styles.ts
  src/pages/CreateBoard/index.tsx
  src/pages/CreateBoard/styles.ts
  src/pages/CreateBoardContent/index.tsx
  src/pages/CreateBoardContent/styles.ts
  src/pages/CreatePost/index.tsx
  src/pages/PostDetail/index.tsx
  src/recoil/atoms/posts.ts
  src/types/board.ts
  src/types/createBoard.ts
  src/types/createPost.ts
Labels: Feat

#55 [chore-54] 콘솔 오류 해결 및 게시물 api response 변경 수정
  src/components/Board/index.tsx
  src/components/Board/styles.ts
  src/components/Filter/index.tsx
  src/components/Filter/styles.ts
  src/components/Modal/index.tsx
  src/components/Modal/styles.ts
  src/components/Review/index.tsx
  src/components/Review/styles.ts
  src/hoc/AuthChecker.tsx
  src/mocks/api/data/boardData.ts
  src/pages/Home.tsx
  src/style/global.js
  src/types/board.ts
Labels: Bugfix, Chore

#56 [feat-52]댓글 작성기능, 게시글 상세 조건 설정
  src/apis/board.ts
  src/apis/comment.ts
  src/components/BoardDetailContent/index.tsx
  src/components/BoardDetailContent/styles.ts
  src/components/BoardDetailOption/index.tsx
  src/components/BoardDetailOption/styles.ts
  src/components/Calendar/index.tsx
  src/components/CommentDisplay/index.tsx
  src/components/CommentDisplay/styles.ts
  src/components/CommentInput/index.tsx
  src/components/CommentInput/styles.ts
  src/components/SelectBoardOption/index.tsx
  src/components/UpdateBoard/index.tsx
  src/components/common/Textarea/index.tsx
  src/components/common/Textarea/styles.ts
  src/mocks/api/comment.ts
  src/mocks/api/data/boardDetailData.ts
  src/mocks/api/data/comment.ts
  src/pages/BoardDetail/index.tsx
  src/pages/CreateBoardContent/index.tsx
  src/types/board.ts
  src/types/comment.ts
Labels: Feat

#58 [refac-53] 서버 데이터 react-query로 관리하도록 변경 완료
  src/apis/auth.ts
  src/apis/board.ts
  src/components/BabTemp/index.tsx
  src/components/Board/index.tsx
  src/components/ProfileInfo/index.tsx
  src/components/Review/index.tsx
  src/components/SideBar/index.tsx
  src/hoc/AuthChecker.tsx
  src/pages/BoardDetail/index.tsx
  src/pages/Home.tsx
  src/pages/Profile/index.tsx
  src/pages/Reviews.tsx
  src/pages/SignIn.tsx
  src/recoil/atoms/user.ts
  src/utils/limit.ts
Labels: Refac

#59 [feat-57]게시글 참여하기 구현, 로그인 되지 않은 유저 로그인 모달 호출
  src/apis/board.ts
  src/assets/images/svg/cancel.svg
  src/components/BoardDetailContent/index.tsx
  src/components/BoardDetailContent/styles.ts
  src/components/Calendar/index.tsx
  src/components/Calendar/styles.ts
  src/components/CommentInput/index.tsx
  src/components/KakaoStaticMap/index.tsx
  src/components/Modal/BoardDelete/index.tsx
  src/components/Modal/BoardDelete/styles.ts
  src/components/Modal/KakaoMap/index.tsx
  src/components/Modal/KakaoMap/styles.ts
  src/components/ProfileInfo/index.tsx
  src/components/ProfileInfo/styles.ts
  src/components/SelectBoardOption/index.tsx
  src/components/SelectBoardOption/styles.ts
  src/components/UpdateBoard/index.tsx
  src/components/UpdateBoard/styles.ts
  src/components/common/Input/index.tsx
  src/components/common/Textarea/index.tsx
  src/pages/BoardDetail/index.tsx
  src/pages/CreateBoard/styles.ts
  src/pages/CreateBoardContent/index.tsx
  src/pages/CreateBoardContent/styles.ts
  src/recoil/atoms/mapData.ts
  src/recoil/atoms/modal.ts
  src/recoil/atoms/posts.ts
  src/types/board.ts
  src/types/createBoard.ts
  src/types/mapData.ts
  src/utils/limit.ts
Labels: Feat

#62 [feat-61] GitHub Action 자동배포 main.yml 파일생성
  .github/workflows/main.yml
Labels: Feat

#63 [feat-60] 사용자가 참여한 게시물 확인하기 기능 완료 및 후기 작성 페이지 구현
  src/Router.tsx
  src/apis/board.ts
  src/assets/images/svg/page.svg
  src/assets/images/svg/square.svg
  src/components/BabTemp/index.tsx
  src/components/Board/index.tsx
  src/components/Board/styles.ts
  src/components/Modal/Review/index.tsx
  src/components/Modal/Review/styles.ts
  src/components/SideBarContent/index.tsx
  src/components/SideBarContent/styles.ts
  src/mocks/api/board.ts
  src/mocks/api/data/boardData.ts
  src/pages/JoinedMeetings.tsx
  src/recoil/atoms/modal.ts
  src/types/board.ts
Labels: Feat

#66 [fix-64] 배포 환경에서 로그인 안되는 문제 해결 및 로그아웃 기능 구현
  src/apis/auth.ts
  src/components/SideBar/index.tsx
  src/hoc/AuthChecker.tsx
  src/pages/SignIn.tsx
Labels: Bugfix, Feat
